#!/usr/bin/env python3

import sys
import re
from subprocess import check_output
def main():
    commit_msg_filepath = sys.argv[1]
    branch = check_output(
        ["git", "symbolic-ref", "--short", "HEAD"]
    ).strip().decode()


    regex = "[A-Z]{2,7}-[0-9]{1,7}"
    tickets= re.findall(regex, branch)
    if len(tickets) == 0:
        return
    print("tickets", tickets)

    with open(commit_msg_filepath, "r+") as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        for ticket in tickets:
            if ticket in commit_msg:
                print("skip", ticket)
                continue
            commit_msg =f"[{ticket}] {commit_msg}"
            print("add ticket", commit_msg)
        fh.write(commit_msg)


main()
